name: regression

on: workflow_dispatch

jobs:
  test:
    environment: ci
    env:
      GITHUB_TOKEN: ${secrets.GITHUB_TOKEN}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run wdio
