name: change detection

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ci
    env:
      GITHUB_TOKEN: ${secrets.GITHUB_TOKEN}
      CKAN_KEY: ${secrets.CKAN_KEY}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run wdio
