on:
  pull_request:
    types:
      - opened
name: Notify Slack
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: github-bot
        SLACK_CHANNEL: nhsx
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: ${{ github.event.pull_request.title }}
        SLACK_MESSAGE: |
          ${{ github.event.pull_request.body }}
          ${{ github.event.pull_request.html_url }}
        MSG_MINIMAL: "true"
